# Generated by Django 3.1.3 on 2020-12-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_management', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='c_name',
            new_name='c_username',
        ),
    ]
