# Generated by Django 3.1.3 on 2020-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_management', '0003_auto_20201222_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('c_email', models.EmailField(max_length=20)),
                ('c_subject', models.CharField(max_length=100)),
                ('c_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
