# Generated by Django 3.1.3 on 2020-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_management', '0004_auto_20201222_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_e',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
