# Generated by Django 3.1.3 on 2020-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_management', '0005_blog_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registered',
            name='user_image',
            field=models.ImageField(default='', upload_to='user_image'),
        ),
    ]
