# Generated by Django 3.1.3 on 2020-12-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_data',
            name='mainbank',
            field=models.BooleanField(blank=True),
        ),
    ]
