# Generated by Django 3.1.3 on 2020-12-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0003_auto_20201221_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_data',
            name='bankcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bank_data',
            name='mainbank',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='bank_data',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
