# Generated by Django 3.1.3 on 2020-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0004_auto_20201221_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_data',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bank_data',
            name='mainbank',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
