# Generated by Django 3.1.3 on 2020-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0005_auto_20201221_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=20)),
                ('numberofbranch', models.CharField(max_length=20)),
            ],
        ),
    ]
