# Generated by Django 3.1.3 on 2020-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0006_main_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_bank',
            name='numberofbranch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
