# Generated by Django 3.1.3 on 2020-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0007_auto_20201221_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_bank',
            name='bankname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
