# Generated by Django 3.1.3 on 2020-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0011_auto_20201221_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_bank',
            name='numberofbranch',
            field=models.CharField(blank='0', max_length=20),
        ),
    ]
