# Generated by Django 3.1.3 on 2020-12-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0013_auto_20201221_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_bank',
            name='bankname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='main_bank',
            name='numberofbranch',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
