# Generated by Django 3.1.3 on 2020-12-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0014_auto_20201221_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_bank',
            name='main_bank_id',
            field=models.CharField(default='', max_length=8),
        ),
    ]
