# Generated by Django 3.1.3 on 2020-12-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0017_blog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_detail',
            name='b_image',
            field=models.ImageField(default='', upload_to='blog_images'),
        ),
    ]
