# Generated by Django 3.1.3 on 2020-12-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin_management', '0018_blog_detail_b_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='add_blog_in',
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
    ]
