# Generated by Django 3.1.3 on 2020-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan_request_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_primery_id', models.CharField(max_length=10)),
                ('approved_loan', models.CharField(default='Peanding', max_length=10)),
                ('loantype', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('radio', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('maritalstatus', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('professional', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('income', models.CharField(max_length=100)),
                ('l_amount', models.CharField(max_length=100)),
                ('l_tenure', models.CharField(max_length=100)),
                ('l_interest_rate', models.CharField(max_length=50)),
            ],
        ),
    ]
