# Generated by Django 3.1.3 on 2020-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_request_list',
            name='b1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loan_request_list',
            name='b2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loan_request_list',
            name='b3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
