# Generated by Django 3.1.3 on 2020-12-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20201221_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_request_list',
            name='b1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loan_request_list',
            name='b2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loan_request_list',
            name='b3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
