# Generated by Django 3.1.3 on 2020-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20201221_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_request_list',
            name='b1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan_request_list',
            name='b2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan_request_list',
            name='b3',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
