# Generated by Django 3.1.3 on 2020-12-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20201221_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=20)),
                ('c_email', models.EmailField(max_length=50)),
                ('c_image', models.ImageField(upload_to='user_comment_images')),
                ('c_message', models.CharField(max_length=500)),
                ('c_datetime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
