# Generated by Django 3.1.3 on 2020-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio_file_name',
            field=models.CharField(default='hey', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
