# Generated by Django 3.1.3 on 2020-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20201227_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_request_list',
            name='b2',
        ),
        migrations.RemoveField(
            model_name='loan_request_list',
            name='b3',
        ),
        migrations.AlterField(
            model_name='loan_request_list',
            name='b1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
